package com.app.measurement;

/**
 * Created by bijat on 08.06.2016.
 */
public enum ExecutionTimeName {
    BINARYZATION,
    SEGMANTATION,
    HAND_FEATURE_CALCULATE,
    HAND_FEATURE_FINGERS,
    HAND_FEATURE_CALCULATE_FINGERS,
    HAND_FEATURE_CALCULATE_OTHERS,
    HAND_FEATURE_CALCULATE_OTHERS_AREAS,
    HAND_FEATURE_CALCULATE_OTHERS_CIRCLES,

    BETWEEN_CAPTURE_CAMERA_PREVIEW,
    CAPTURE_CAMERA_PREVIEW_TO_CALCULATE,
    SEGMENTATE_IMAGE_THREAD,
    HAND_FEATURE_THREAD,
    USER_RECOGNICE_THREAD;
}
